targetScope = 'resourceGroup'

// ------------------
//    PARAMETERS
// ------------------

@description('The location where the resources will be created. This needs to be the same region as the Azure Container Apps instances.')
param location string = resourceGroup().location

@description('Optional. The tags to be assigned to the created resources.')
param tags object = {}

@description('Optional. The name of the Container App. If set, it overrides the name generated by the template.')
@minLength(2)
@maxLength(32)
param containerName string

@description('The resource ID of the existing user-assigned managed identity to be assigned to the Container App to be able to pull images from the container registry.')
param containerRegistryUserAssignedIdentityId string

@description('The resource ID of the existing Container Apps environment in which the Container App will be deployed.')
param containerAppsEnvironmentId string

@description('The name of the existing Azure Container Registry.')
param registryServerName string = 'dsscontainerregistrydev'


@description('The name of the existing image.')
param image string

@description('The name of the existing image.')
param workloadProfleName  string = 'wmata-wlp-d4'


// ------------------
// RESOURCES
// ------------------

resource frontendWebAppService 'Microsoft.App/containerApps@2023-05-01' = {
  name: containerName
  location: location
  tags: tags
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
        '${containerRegistryUserAssignedIdentityId}': {}
    }
  }
  properties: {
    managedEnvironmentId: containerAppsEnvironmentId
    workloadProfileName: workloadProfleName
    configuration: {
      activeRevisionsMode: 'single'
      ingress: {
        external: false
        targetPort: 3001
      }
      registries: !empty(registryServerName) ? [
        {
          server: '${registryServerName}.azurecr.io'
          identity: containerRegistryUserAssignedIdentityId
        }
      ] : []
    }
    template: {
      containers: [
        {
          name: containerName
          image: image
          resources: {
            cpu: json('0.5')
            memory: '1Gi'
          }
        }
      ]
      scale: {
        minReplicas: 1
        maxReplicas: 3
      }
    }
  }
}

// ------------------
// OUTPUTS
// ------------------

@description('The FQDN of the "app" Container App.')
output helloWorldAppFqdn string = frontendWebAppService.properties.configuration.ingress.fqdn
