targetScope = 'resourceGroup'

// ------------------
//    PARAMETERS
// ------------------

@description('The location where the resources will be created. This needs to be the same region as the Azure Container Apps instances.')
param location string = resourceGroup().location

@description('Optional. The tags to be assigned to the created resources.')
param tags object = {}

@description('Optional. The name of the Container App. If set, it overrides the name generated by the template.')
@minLength(2)
@maxLength(32)
param helloWorldContainerAppName string = 'digital-signage-content-broker'

@description('The resource ID of the existing user-assigned managed identity to be assigned to the Container App to be able to pull images from the container registry.')
param containerRegistryUserAssignedIdentityId string

@description('The resource ID of the existing Container Apps environment in which the Container App will be deployed.')
param containerAppsEnvironmentId string

@description('Name of the container image to be used for the Container App.')
param containerImageName string

@description('The name of the existing Azure Container Registry.')
param registryServerName string

// ------------------
// RESOURCES
// ------------------

@description('digital-signage-content-broker Container App.')
resource containerApp 'Microsoft.App/containerApps@2023-05-01' = {
  name: digital-signage-content-broker
  location: location
  tags: tags
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${containerRegistryUserAssignedIdentityId}': {}
    }
  }
  properties: {
    configuration: {
      activeRevisionsMode: 'single'
      ingress: {
        allowInsecure: false
        external: false
        targetPort: 3001
        transport: 'auto'
      }
      registries: [
        {
          server: registryServerName
          identity: containerRegistryUserAssignedIdentityId
        }
      ] 
      secrets: []
    }
    environmentId: containerAppsEnvironmentId
    workloadProfileName: 'default'
    template: {
      containers: [
        {
          name: 'digital-signage-content-broker'
          // Production readiness change
          // All workloads should be pulled from your private container registry and not public registries.
          image: containerImageName
          resources: {
            cpu: json('0.5')
            memory: '1Gi'
          }
        }
      ]
      scale: {
        minReplicas: 1
        maxReplicas: 2
      }
      volumes: []
    }
  }
}

// ------------------
// OUTPUTS
// ------------------

@description('The FQDN of the "Hello World" Container App.')
output helloWorldAppFqdn string = containerApp.properties.configuration.ingress.fqdn
