targetScope = 'resourceGroup'

// ------------------
//    PARAMETERS
// ------------------

@description('The location where the resources will be created. This needs to be the same region as the Azure Container Apps instances.')
param location string = resourceGroup().location

@description('Optional. The tags to be assigned to the created resources.')
param tags object = {}

@description('Optional. The name of the Container App. If set, it overrides the name generated by the template.')
@minLength(2)
@maxLength(32)
param frontendWebAppServiceName string = 'digital-signage-content-broker'

@description('The resource ID of the existing user-assigned managed identity to be assigned to the Container App to be able to pull images from the container registry.')
param containerRegistryUserAssignedIdentityId string

@description('The resource ID of the existing Container Apps environment in which the Container App will be deployed.')
param containerAppsEnvironmentId string

@description('The name of the existing Azure Container Registry.')
param registryServerName string = 'dsscontainerregistrydev'


@description('The name of the existing image.')
param frontendWebAppServiceImage  string = 'dsscontainerregistrydev.azurecr.io/wmata/digital-signage-content-broker:1.0'

@description('The name of the existing image.')
param workloadProfleName  string = 'wmata-wlp-d4'


// ------------------
// RESOURCES
// ------------------

// @description('The "Hello World" Container App.')
// resource containerApp 'Microsoft.App/containerApps@2023-05-01' = {
//   name: helloWorldContainerAppName
//   location: location
//   tags: tags
//   identity: {
//     type: 'UserAssigned'
//     userAssignedIdentities: {
//       '${containerRegistryUserAssignedIdentityId}': {}
//     }
//   }
//   properties: {
//     configuration: {
//       activeRevisionsMode: 'single'
//       ingress: {
//         allowInsecure: false
//         external: true
//         targetPort: 80
//         transport: 'auto'
//       }
//       registries: [
//         {
//           server: registryServerName
//           identity: containerRegistryUserAssignedIdentityId
//         }
//       ] 
//       secrets: []
//     }
//     environmentId: containerAppsEnvironmentId
//     workloadProfileName: 'Consumption'
//     template: {
//       containers: [
//         {
//           name: 'simple-hello-pythin-app'
//           // Production readiness change
//           // All workloads should be pulled from your private container registry and not public registries.
//           image: containerImageName
//           resources: {
//             cpu: json('0.25')
//             memory: '0.5Gi'
//           }
//         }
//       ]
//       scale: {
//         minReplicas: 1
//         maxReplicas: 10
//       }
//       volumes: []
//     }
//   }
// }


resource frontendWebAppService 'Microsoft.App/containerApps@2023-05-01' = {
  name: frontendWebAppServiceName
  location: location
  tags: tags
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
        '${containerRegistryUserAssignedIdentityId}': {}
    }
  }
  properties: {
    managedEnvironmentId: containerAppsEnvironmentId
    workloadProfileName: workloadProfleName
    configuration: {
      activeRevisionsMode: 'single'
      ingress: {
        external: false
        targetPort: 3001
      }
      registries: !empty(registryServerName) ? [
        {
          server: '${registryServerName}.azurecr.io'
          identity: containerRegistryUserAssignedIdentityId
        }
      ] : []
    }
    template: {
      containers: [
        {
          name: frontendWebAppServiceName
          image: frontendWebAppServiceImage
          resources: {
            cpu: json('0.5')
            memory: '1Gi'
          }
        }
      ]
      scale: {
        minReplicas: 1
        maxReplicas: 3
      }
    }
  }
}

// ------------------
// OUTPUTS
// ------------------

@description('The FQDN of the "app" Container App.')
output helloWorldAppFqdn string = frontendWebAppService.properties.configuration.ingress.fqdn
